# Generated by Django 3.0.8 on 2020-07-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('highest_education', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=500)),
                ('current_skills', models.CharField(max_length=500)),
                ('aspiring_skills', models.CharField(max_length=500)),
                ('aspiring_role', models.CharField(max_length=150)),
                ('dream_company', models.CharField(max_length=150)),
                ('careers_trajectories', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('create_an_account', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
