# Generated by Django 3.0.8 on 2020-07-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
